trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'dockerhub-conn' # назва вашого Service Connection
  imageRepository: 'gitmate0/lab1-fastapi-crud'

stages:

  # -----------------------------------------------------------------
  # Stage a: Збирання проєкту (uv)
  # -----------------------------------------------------------------
  - stage: Build
    displayName: 'a. Збирання проєкту'
    jobs:
      - job: BuildJob
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.12'

          - script: |
              curl -LsSf https://astral.sh/uv/install.sh | sh
              echo "##vso[task.prependpath]$HOME/.local/bin"
              uv pip install --system -r requirements.txt
            displayName: 'Перевірка залежностей через uv'

  # -----------------------------------------------------------------
  # Stage b: Запуск unit-тестів (uv)
  # -----------------------------------------------------------------
  - stage: Test
    displayName: 'b. Запуск unit-тестів'
    dependsOn: Build
    jobs:
      - job: TestJob
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.12'

          - script: |
              curl -LsSf https://astral.sh/uv/install.sh | sh
              echo "##vso[task.prependpath]$HOME/.local/bin"
              uv pip install --system -r requirements.txt pytest pytest-cov
              uv run pytest --junitxml=test-results.xml
            displayName: 'Запуск pytest'

          - task: PublishTestResults@2
            condition: succeededOrFailed()
            inputs:
              testResultsFiles: '**/test-results.xml'

  # -----------------------------------------------------------------
  # Stage c, d, e: Збирання, Тегування та Публікація в Docker Hub
  # -----------------------------------------------------------------
  - stage: DockerPublish
    displayName: 'c-e. Збирання, тегування та публікація Docker-образу'
    dependsOn: Test
    jobs:
      - job: BuildAndPushJob
        displayName: 'Build and Push to Docker Hub'
        steps:
          - task: Docker@2
            displayName: 'c, d, e. Build, Tag and Push'
            inputs:
              containerRegistry: '$(dockerRegistryServiceConnection)'
              repository: '$(imageRepository)'
              command: 'buildAndPush'
              dockerfile: '**/Dockerfile'
              tags: |
                $(Build.BuildId)
                latest
                v1.0